export const LogType = {
  USER_JOINED: "USER_JOINED",
  ITEM_ADDED: "ITEM_ADDED",
  ITEM_REMOVED: "ITEM_REMOVED",
  ITEM_COMPLETED: "ITEM_COMPLETED",
  ITEM_INCOMPLETED: "ITEM_INCOMPLETED",
}

export const ItemStatus = {
  DONE: "DONE",
  PENDING: "PENDING",
}
